import { Post, User, NewsItem, Community, Chat, Pitch } from "./types";

export const CURRENT_USER: User = {
  id: "u1",
  name: "Alex Rivera",
  username: "arivera_dev",
  role: "Product-Focused Founder",
  company: "Nexen",
  avatar: "/default-avatar.svg",
  bio: "Building Nexen to connect the next generation of founders. #BuildInPublic #Startups",
  followingIds: ["u2", "u4"],
  followerIds: ["u3", "u5", "u6"],
};

export const INITIAL_PITCHES: Pitch[] = [
  {
    id: "pitch0",
    userId: "u6",
    user: {
      id: "u6",
      name: "Aarav Mehta",
      username: "aarav_m",
      role: "Sustainability Founder",
      company: "EcoStream",
      avatar: "https://picsum.photos/id/103/200/200",
      bio: "Building tech for a greener future.",
      followingIds: [],
      followerIds: [],
    },
    title: "EcoStream: AI-Powered Waste Management",
    description:
      "EcoStream uses AI to optimize waste collection routes and recycling processes, reducing operational costs and environmental impact for smart cities.",
    votes: 124,
    comments: 3,
    commentList: [],
    category: "Sustainability",
    timestamp: "1h ago",
    votedBy: [],
    isTrending: true,
    supportersCount: 42,
  },
  {
    id: "pitch1",
    userId: "u1",
    user: CURRENT_USER,
    title: "AI-Powered Code Review for Startups",
    description:
      "Early-stage startups can't afford senior engineers for code reviews. This AI tool learns your codebase and provides contextual, actionable feedback in real-time.",
    votes: 342,
    comments: 12,
    commentList: [
      {
        id: "pc1",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sarah Chen",
          username: "schen_dev",
          role: "CTO & Co-founder",
          company: "CloudScale",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Building scalable infrastructure for the next billion users.",
          followingIds: [],
          followerIds: [],
        },
        text: "This would save us so much time during PRs!",
        timestamp: "2h ago",
      },
    ],
    category: "DevTools",
    timestamp: "3h ago",
    votedBy: [],
    isTrending: true,
    supportersCount: 89,
  },
  {
    id: "pitch2",
    userId: "u4",
    user: {
      id: "u4",
      name: "Maya Johnson",
      username: "mayaj",
      role: "Serial Founder",
      company: "SoloSaaS",
      avatar: "https://picsum.photos/id/102/200/200",
      bio: "Building and scaling micro-SaaS products.",
      followingIds: [],
      followerIds: [],
    },
    title: "Micro-SaaS Marketplace for Solopreneurs",
    description:
      "Solopreneurs spend months building SaaS products that already exist. This curated marketplace helps them find, buy, and customize battle-tested micro-SaaS solutions.",
    votes: 278,
    comments: 8,
    commentList: [],
    category: "Marketplace",
    timestamp: "6h ago",
    votedBy: ["u1"],
    isTrending: true,
    supportersCount: 124,
  },
  {
    id: "pitch3",
    userId: "u5",
    user: {
      id: "u5",
      name: "James Wilson",
      username: "jwilson",
      role: "Fintech Founder",
      company: "PayFlow",
      avatar: "https://picsum.photos/id/101/200/200",
      bio: "Reimagining financial systems for the modern age.",
      followingIds: [],
      followerIds: [],
    },
    title: "Fractional CFO Dashboard for Gen Z",
    description:
      "Traditional accounting software is too complex for the new wave of creative entrepreneurs. This dashboard automates tax savings and cash flow forecasting with a 1-tap interface.",
    votes: 156,
    comments: 5,
    commentList: [],
    category: "Fintech",
    timestamp: "1d ago",
    votedBy: [],
    supportersCount: 45,
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: "p6",
    userId: "u6",
    user: {
      id: "u6",
      name: "Aarav Mehta",
      username: "aarav_builds",
      role: "First-time Founder",
      company: "EcoStream",
      avatar: "https://picsum.photos/id/103/200/200",
      bio: "Ex-Google PM. Now building EcoStream to decarbonize supply chains.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Honestly struggling with the 'cold start' problem. We've built the MVP for EcoStream, but getting the first 10 paying B2B customers feels like a mountain. \n\nShould I focus on cold LinkedIn outreach or try to build an audience first? Any experienced founders here who've cracked the 0 to 1 journey? 🙏",
    likes: 42,
    comments: 1,
    commentList: [
      {
        id: "c4",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "Aarav, don't wait to build an audience—that takes months. For your first 10:\n\n1. Use LinkedIn Sales Navigator to find 50 people with the exact pain point.\n2. Send ultra-personalized videos (Loom) showing how you solve their specific problem.\n3. Offer a 'Beta Partner' discount in exchange for deep feedback.\n\nDo things that don't scale. Audience building is for when you're going from 10 to 1000. Keep pushing! 🚀",
        timestamp: "15m ago",
      },
      {
        id: "c_p6_2",
        userId: "u4",
        user: {
          id: "u4",
          name: "Marc Lou",
          username: "marclou",
          role: "Serial Founder",
          company: "SoloSaaS",
          avatar: "https://picsum.photos/id/102/200/200",
          bio: "Building and scaling micro-SaaS products.",
          followingIds: [],
          followerIds: [],
        },
        text: "Sahil is spot on. I got my first 10 for SoloSaaS by literally DMing people on Twitter who were complaining about their current tools. It's unglamorous but it works.",
        timestamp: "5m ago",
      },
    ],
    reposts: 3,
    reposterList: [],
    timestamp: "2h ago",
    tags: ["FoundersHelp", "B2BSaaS", "ZeroToOne"],
  },
  {
    id: "p1",
    userId: "u2",
    user: {
      id: "u2",
      name: "Sahil Bloom",
      username: "sahil_builds",
      role: "Founder",
      company: "GrowthLoop",
      avatar: "https://picsum.photos/id/65/200/200",
      bio: "Scaling tech startups from 0 to 1.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Just closed our first enterprise pilot! 🚀 It took 4 months of negotiation, but the feedback on our core value proposition was worth it. Scaling the sales team is next. #Founders #StartupLife #Growth",
    image: "https://picsum.photos/id/1/800/400",
    likes: 142,
    comments: 2,
    commentList: [
      {
        id: "c1",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "Huge win, Sahil! Enterprise sales is a different beast. How are you planning to handle the custom integration requests?",
        timestamp: "1h ago",
      },
      {
        id: "c_p1_2",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "We're being very selective. If it doesn't fit the long-term roadmap, we're saying no. Focus is key right now.",
        timestamp: "30m ago",
      },
    ],
    reposts: 1,
    reposterList: [],
    timestamp: "3h ago",
    tags: ["Sales", "Enterprise", "Growth"],
  },
  {
    id: "p2",
    userId: "u4",
    user: {
      id: "u4",
      name: "Marc Lou",
      username: "marclou",
      role: "Serial Founder",
      company: "SoloSaaS",
      avatar: "https://picsum.photos/id/102/200/200",
      bio: "Building and scaling micro-SaaS products.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Indie hacking is 10% coding and 90% fighting the urge to start a second project before finishing the first one. Who's with me? 😂 #IndieHackers #SaaS",
    likes: 312,
    comments: 45,
    commentList: [
      {
        id: "c_p2_1",
        userId: "u1",
        user: CURRENT_USER,
        text: "I literally have 15 unfinished projects in my 'drafts' folder. The struggle is real! 😂",
        timestamp: "2h ago",
      },
      {
        id: "c_p2_2",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "Focus is a superpower in this industry. Shipping is the only feature that matters!",
        timestamp: "1h ago",
      },
    ],
    reposts: 89,
    reposterList: [CURRENT_USER],
    timestamp: "4h ago",
    tags: ["Startup", "Growth"],
  },
  {
    id: "p3",
    userId: "u1",
    user: CURRENT_USER,
    content:
      "Just experimented with leveraging Gemini 2.5 Flash to automate our Tier 1 customer support. The reduction in response time is staggering. This isn't just a tech upgrade; it's a fundamental shift in our unit economics. 🎙️✨",
    likes: 89,
    comments: 12,
    commentList: [
      {
        id: "c3",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "This is huge for margins. How are you handling the 'hallucination' risk in customer-facing responses?",
        timestamp: "30m ago",
      },
      {
        id: "c_p3_2",
        userId: "u1",
        user: CURRENT_USER,
        text: "We're using a 'human-in-the-loop' system for high-value accounts, but for general FAQs, the grounding metadata is keeping it very accurate. The ROI is already clear.",
        timestamp: "10m ago",
      },
    ],
    reposts: 5,
    reposterList: [],
    timestamp: "5h ago",
    tags: ["AI", "Efficiency", "SaaS"],
  },
  {
    id: "p_u1_1",
    userId: "u1",
    user: CURRENT_USER,
    content:
      "We just survived our first major traffic spike after a viral mention. The team stayed up all night, but the infrastructure held. Scaling is a high-class problem, but it's still a problem! 🚀",
    likes: 120,
    comments: 15,
    commentList: [
      {
        id: "c_u1_1_1",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "Congrats on surviving! Did you have to implement any emergency rate limiting?",
        timestamp: "45m ago",
      },
      {
        id: "c_u1_1_2",
        userId: "u1",
        user: CURRENT_USER,
        text: "We did. We also had to spin up extra database replicas. It was a great stress test for our upcoming official launch.",
        timestamp: "20m ago",
      },
    ],
    reposts: 5,
    reposterList: [],
    timestamp: "1h ago",
    tags: ["Scaling", "Startups", "Growth"],
  },
  {
    id: "p_u1_2",
    userId: "u1",
    user: CURRENT_USER,
    content:
      "What's everyone's favorite productivity hack? I've been using the Pomodoro technique combined with lo-fi beats and it's been a game changer.",
    likes: 85,
    comments: 32,
    commentList: [
      {
        id: "c_u1_2_1",
        userId: "u4",
        user: {
          id: "u4",
          name: "Marc Lou",
          username: "marclou",
          role: "Serial Founder",
          company: "SoloSaaS",
          avatar: "https://picsum.photos/id/102/200/200",
          bio: "Building and scaling micro-SaaS products.",
          followingIds: [],
          followerIds: [],
        },
        text: "Deep work blocks in the morning. No Slack, no emails until 11 AM.",
        timestamp: "3h ago",
      },
      {
        id: "c_u1_2_2",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "I've started using 'Focus' mode on macOS to hide all non-essential apps. It's simple but very effective for staying in the flow.",
        timestamp: "1h ago",
      },
    ],
    reposts: 2,
    reposterList: [],
    timestamp: "5h ago",
    tags: ["Productivity", "Focus"],
  },
  {
    id: "p_u1_3",
    userId: "u1",
    user: CURRENT_USER,
    content:
      "Debating our long-term data strategy. We're seeing some limitations with our current relational setup as we scale. Has anyone here made the jump to a more flexible architecture mid-growth? Success stories or warnings welcome!",
    likes: 45,
    comments: 18,
    commentList: [
      {
        id: "c_u1_3_1",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "Be careful with 'shiny object syndrome'. Migrating data while growing is like changing tires on a moving car.",
        timestamp: "5h ago",
      },
      {
        id: "c_u1_3_2",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "Agreed. We stuck with our initial setup much longer than we thought we could by just optimizing queries. Don't over-engineer too early.",
        timestamp: "2h ago",
      },
    ],
    reposts: 1,
    reposterList: [],
    timestamp: "1d ago",
    tags: ["Strategy", "Architecture", "Scaling"],
  },
  {
    id: "p_u1_4",
    userId: "u1",
    user: CURRENT_USER,
    content:
      "The hardest part of building a product isn't the code, it's figuring out what NOT to build. Feature bloat is the silent killer of startups.",
    likes: 310,
    comments: 42,
    commentList: [
      {
        id: "c_u1_4_1",
        userId: "u4",
        user: {
          id: "u4",
          name: "Marc Lou",
          username: "marclou",
          role: "Serial Founder",
          company: "SoloSaaS",
          avatar: "https://picsum.photos/id/102/200/200",
          bio: "Building and scaling micro-SaaS products.",
          followingIds: [],
          followerIds: [],
        },
        text: "100% agreed. If you're not embarrassed by your first version, you launched too late.",
        timestamp: "1d ago",
      },
      {
        id: "c_u1_4_2",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "I keep a 'No' list for every project. It's harder to maintain than the roadmap but much more important.",
        timestamp: "12h ago",
      },
    ],
    reposts: 56,
    reposterList: [],
    timestamp: "2d ago",
    tags: ["Product", "Startups"],
  },
  {
    id: "p_u1_5",
    userId: "u1",
    user: CURRENT_USER,
    content:
      "Just finished a deep dive into organizational design for rapidly growing teams. The shift from 'everyone does everything' to specialized roles is painful but necessary. How are you all handling the transition?",
    likes: 150,
    comments: 8,
    commentList: [
      {
        id: "c_u1_5_1",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "It's all about trust. You have to hire people smarter than you and then actually let them do their jobs.",
        timestamp: "2d ago",
      },
      {
        id: "c_u1_5_2",
        userId: "u1",
        user: CURRENT_USER,
        text: "Exactly. Letting go of the 'founder control' is the hardest part of scaling. But it's the only way to grow.",
        timestamp: "1d ago",
      },
    ],
    reposts: 12,
    reposterList: [],
    timestamp: "3d ago",
    tags: ["Leadership", "Scaling", "Founders"],
  },
  {
    id: "p_u2_1",
    userId: "u2",
    user: {
      id: "u2",
      name: "Sahil Bloom",
      username: "sahil_builds",
      role: "Founder",
      company: "GrowthLoop",
      avatar: "https://picsum.photos/id/65/200/200",
      bio: "Scaling tech startups from 0 to 1.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Founder productivity isn't about working 100 hours a week. It's about making 3 high-leverage decisions every day. Manage your energy, not just your time. ☕🚀",
    likes: 540,
    comments: 89,
    commentList: [
      {
        id: "c_u2_1_1",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "So true. A tired founder makes expensive mistakes.",
        timestamp: "1h ago",
      },
      {
        id: "c_u2_1_2",
        userId: "u4",
        user: {
          id: "u4",
          name: "Marc Lou",
          username: "marclou",
          role: "Serial Founder",
          company: "SoloSaaS",
          avatar: "https://picsum.photos/id/102/200/200",
          bio: "Building and scaling micro-SaaS products.",
          followingIds: [],
          followerIds: [],
        },
        text: "I've started taking 'strategy walks' without my phone. Best ROI on my time lately.",
        timestamp: "30m ago",
      },
    ],
    reposts: 120,
    reposterList: [],
    timestamp: "2h ago",
    tags: ["Productivity", "Founders"],
  },
  {
    id: "p_u2_2",
    userId: "u2",
    user: {
      id: "u2",
      name: "Sahil Bloom",
      username: "sahil_builds",
      role: "Founder",
      company: "GrowthLoop",
      avatar: "https://picsum.photos/id/65/200/200",
      bio: "Scaling tech startups from 0 to 1.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "The importance of attention to detail: We found a tiny friction point in our onboarding flow that was causing a 15% drop-off. Fixed it yesterday and conversion is already up. Small tweaks, big impact.",
    likes: 890,
    comments: 150,
    commentList: [
      {
        id: "c_u2_2_1",
        userId: "u1",
        user: CURRENT_USER,
        text: "Onboarding is where most startups lose their users. Great catch!",
        timestamp: "4h ago",
      },
      {
        id: "c_u2_2_2",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "User psychology is fascinating. Sometimes just changing the color of a button or the wording of a CTA can change everything.",
        timestamp: "2h ago",
      },
    ],
    reposts: 230,
    reposterList: [],
    timestamp: "6h ago",
    tags: ["Product", "UX", "Growth"],
  },
  {
    id: "p_u2_3",
    userId: "u2",
    user: {
      id: "u2",
      name: "Sahil Bloom",
      username: "sahil_builds",
      role: "Founder",
      company: "GrowthLoop",
      avatar: "https://picsum.photos/id/65/200/200",
      bio: "Scaling tech startups from 0 to 1.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Navigating the hype cycle: Every week there's a new 'must-use' tool for startups. As a founder, the hardest part is knowing when to ignore the noise and stick to what works. Focus is a competitive advantage.",
    likes: 1200,
    comments: 340,
    commentList: [
      {
        id: "c_u2_3_1",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "It's definitely exhausting. We've decided to only adopt new tech when it solves a problem we're actually facing today.",
        timestamp: "12h ago",
      },
      {
        id: "c_u2_3_2",
        userId: "u4",
        user: {
          id: "u4",
          name: "Marc Lou",
          username: "marclou",
          role: "Serial Founder",
          company: "SoloSaaS",
          avatar: "https://picsum.photos/id/102/200/200",
          bio: "Building and scaling micro-SaaS products.",
          followingIds: [],
          followerIds: [],
        },
        text: "Shiny object syndrome is the biggest threat to productivity. Pick a stack and master it.",
        timestamp: "6h ago",
      },
    ],
    reposts: 450,
    reposterList: [],
    timestamp: "1d ago",
    tags: ["Focus", "Startups", "Strategy"],
  },
  {
    id: "p_u2_4",
    userId: "u2",
    user: {
      id: "u2",
      name: "Sahil Bloom",
      username: "sahil_builds",
      role: "Founder",
      company: "GrowthLoop",
      avatar: "https://picsum.photos/id/65/200/200",
      bio: "Scaling tech startups from 0 to 1.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Remote work has its perks, but I do miss the spontaneous whiteboard sessions with the team. How do you replicate that online?",
    likes: 450,
    comments: 120,
    commentList: [
      {
        id: "c_u2_4_1",
        userId: "u6",
        user: {
          id: "u6",
          name: "Aarav Mehta",
          username: "aarav_builds",
          role: "First-time Founder",
          company: "EcoStream",
          avatar: "https://picsum.photos/id/103/200/200",
          bio: "Ex-Google PM. Now building EcoStream to decarbonize supply chains.",
          followingIds: [],
          followerIds: [],
        },
        text: "We use Miro and it works pretty well, but nothing beats the physical board.",
        timestamp: "1d ago",
      },
      {
        id: "c_u2_4_2",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "Excalidraw is my go-to. It feels much more like a real whiteboard because of the hand-drawn style.",
        timestamp: "12h ago",
      },
    ],
    reposts: 45,
    reposterList: [],
    timestamp: "2d ago",
    tags: ["RemoteWork", "Collaboration"],
  },
  {
    id: "p_u2_5",
    userId: "u2",
    user: {
      id: "u2",
      name: "Sahil Bloom",
      username: "sahil_builds",
      role: "Founder",
      company: "GrowthLoop",
      avatar: "https://picsum.photos/id/65/200/200",
      bio: "Scaling tech startups from 0 to 1.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Just hit 1000 active users! It's a small milestone, but seeing people actually use what you built is the best feeling in the world.",
    likes: 2300,
    comments: 450,
    commentList: [
      {
        id: "c_u2_5_1",
        userId: "u1",
        user: CURRENT_USER,
        text: "Huge congrats! The first 1000 are always the hardest. Onwards and upwards! 🚀",
        timestamp: "2d ago",
      },
      {
        id: "c_u2_5_2",
        userId: "u4",
        user: {
          id: "u4",
          name: "Marc Lou",
          username: "marclou",
          role: "Serial Founder",
          company: "SoloSaaS",
          avatar: "https://picsum.photos/id/102/200/200",
          bio: "Building and scaling micro-SaaS products.",
          followingIds: [],
          followerIds: [],
        },
        text: "Welcome to the 1k club! Now the real work begins. Watch out for the 'trough of sorrow'!",
        timestamp: "1d ago",
      },
    ],
    reposts: 120,
    reposterList: [],
    timestamp: "3d ago",
    tags: ["Milestone", "Startups"],
  },
  {
    id: "p_u3_1",
    userId: "u3",
    user: {
      id: "u3",
      name: "Divya Sharma",
      username: "divya_codes",
      role: "Technical Co-founder",
      company: "DesignFlow",
      avatar: "https://picsum.photos/id/177/200/200",
      bio: "Building the future of collaborative design.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "The impact of design on conversion: We just finished a major UI overhaul and the initial data shows a 20% increase in sign-up completion. Design isn't just how it looks, it's how it works for the business.",
    likes: 340,
    comments: 56,
    commentList: [
      {
        id: "c_u3_1_1",
        userId: "u1",
        user: CURRENT_USER,
        text: "Design is a competitive advantage. Most B2B tools are so clunky, a good UI really stands out.",
        timestamp: "2h ago",
      },
      {
        id: "c_u3_1_2",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "Exactly! We're proving that enterprise software doesn't have to be ugly to be powerful.",
        timestamp: "1h ago",
      },
    ],
    reposts: 45,
    reposterList: [],
    timestamp: "3h ago",
    tags: ["Design", "Growth", "SaaS"],
  },
  {
    id: "p_u3_2",
    userId: "u3",
    user: {
      id: "u3",
      name: "Divya Sharma",
      username: "divya_codes",
      role: "Technical Co-founder",
      company: "DesignFlow",
      avatar: "https://picsum.photos/id/177/200/200",
      bio: "Building the future of collaborative design.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Building an inclusive product from day one: Accessibility isn't just a compliance checkbox, it's about expanding your market and doing the right thing. It's a core part of our mission.",
    likes: 890,
    comments: 45,
    commentList: [
      {
        id: "c_u3_2_1",
        userId: "u4",
        user: {
          id: "u4",
          name: "Marc Lou",
          username: "marclou",
          role: "Serial Founder",
          company: "SoloSaaS",
          avatar: "https://picsum.photos/id/102/200/200",
          bio: "Building and scaling micro-SaaS products.",
          followingIds: [],
          followerIds: [],
        },
        text: "Preach! A better product for everyone is a win for the business too.",
        timestamp: "4h ago",
      },
      {
        id: "c_u3_2_2",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "It's also good business. You're literally expanding your TAM by making your site accessible.",
        timestamp: "2h ago",
      },
    ],
    reposts: 120,
    reposterList: [],
    timestamp: "8h ago",
    tags: ["Mission", "Inclusion", "Startups"],
  },
  {
    id: "p_u3_3",
    userId: "u3",
    user: {
      id: "u3",
      name: "Divya Sharma",
      username: "divya_codes",
      role: "Technical Co-founder",
      company: "DesignFlow",
      avatar: "https://picsum.photos/id/177/200/200",
      bio: "Building the future of collaborative design.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Tools that help our lean team move faster: We just integrated a new automated testing suite that's saving us 10 hours of manual QA every week. Speed is our biggest advantage.",
    likes: 120,
    comments: 34,
    commentList: [
      {
        id: "c_u3_3_1",
        userId: "u1",
        user: CURRENT_USER,
        text: "Automation is the only way to scale a small team. What tool are you using?",
        timestamp: "5h ago",
      },
      {
        id: "c_u3_3_2",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "We're using Playwright for E2E tests. The developer experience is fantastic and it's caught so many regressions already.",
        timestamp: "3h ago",
      },
    ],
    reposts: 5,
    reposterList: [],
    timestamp: "1d ago",
    tags: ["Efficiency", "Scaling", "Tools"],
  },
  {
    id: "p_u3_4",
    userId: "u3",
    user: {
      id: "u3",
      name: "Divya Sharma",
      username: "divya_codes",
      role: "Technical Co-founder",
      company: "DesignFlow",
      avatar: "https://picsum.photos/id/177/200/200",
      bio: "Building the future of collaborative design.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "The hidden cost of technical debt: We spent the last two weeks refactoring our build process because it was slowing down our deployment cycle. It felt like a waste of time, but our shipping velocity has already doubled.",
    likes: 560,
    comments: 120,
    commentList: [
      {
        id: "c_u3_4_1",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "Technical debt is like a high-interest loan. If you don't pay it back, it will eventually bankrupt your productivity.",
        timestamp: "1d ago",
      },
      {
        id: "c_u3_4_2",
        userId: "u4",
        user: {
          id: "u4",
          name: "Marc Lou",
          username: "marclou",
          role: "Serial Founder",
          company: "SoloSaaS",
          avatar: "https://picsum.photos/id/102/200/200",
          bio: "Building and scaling micro-SaaS products.",
          followingIds: [],
          followerIds: [],
        },
        text: "Exactly. We're now much more intentional about what we build 'quick and dirty' vs what we build to last.",
        timestamp: "12h ago",
      },
    ],
    reposts: 89,
    reposterList: [],
    timestamp: "2d ago",
    tags: ["TechDebt", "Velocity", "Founders"],
  },
  {
    id: "p_u3_5",
    userId: "u3",
    user: {
      id: "u3",
      name: "Divya Sharma",
      username: "divya_codes",
      role: "Technical Co-founder",
      company: "DesignFlow",
      avatar: "https://picsum.photos/id/177/200/200",
      bio: "Building the future of collaborative design.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "The best way to validate a startup idea is to build a minimum viable version and get it in front of users. Surveys and landing pages are great, but nothing beats real usage data.",
    likes: 450,
    comments: 23,
    commentList: [
      {
        id: "c_u3_5_1",
        userId: "u4",
        user: {
          id: "u4",
          name: "Marc Lou",
          username: "marclou",
          role: "Serial Founder",
          company: "SoloSaaS",
          avatar: "https://picsum.photos/id/102/200/200",
          bio: "Building and scaling micro-SaaS products.",
          followingIds: [],
          followerIds: [],
        },
        text: "Build, launch, learn, repeat. The faster the cycle, the better.",
        timestamp: "2d ago",
      },
      {
        id: "c_u3_5_2",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "I call it 'Just-in-time validation'. Don't spend months building something nobody wants.",
        timestamp: "1d ago",
      },
    ],
    reposts: 45,
    reposterList: [],
    timestamp: "4d ago",
    tags: ["Validation", "MVP", "Startups"],
  },
  {
    id: "p_u4_1",
    userId: "u4",
    user: {
      id: "u4",
      name: "Marc Lou",
      username: "marclou",
      role: "Serial Founder",
      company: "SoloSaaS",
      avatar: "https://picsum.photos/id/102/200/200",
      bio: "Building and scaling micro-SaaS products.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Just launched my 5th micro-SaaS this year. It's not about the ideas, it's about the execution and shipping fast.",
    likes: 890,
    comments: 120,
    commentList: [
      {
        id: "c_u4_1_1",
        userId: "u6",
        user: {
          id: "u6",
          name: "Aarav Mehta",
          username: "aarav_builds",
          role: "First-time Founder",
          company: "EcoStream",
          avatar: "https://picsum.photos/id/103/200/200",
          bio: "Ex-Google PM. Now building EcoStream to decarbonize supply chains.",
          followingIds: [],
          followerIds: [],
        },
        text: "Inspiring work, Marc! Your shipping speed is legendary.",
        timestamp: "2h ago",
      },
      {
        id: "c_u4_1_2",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "How do you avoid burnout with that pace? I'm struggling to ship one project every 3 months!",
        timestamp: "1h ago",
      },
    ],
    reposts: 230,
    reposterList: [],
    timestamp: "4h ago",
    tags: ["IndieHacker", "Launch"],
  },
  {
    id: "p_u4_2",
    userId: "u4",
    user: {
      id: "u4",
      name: "Marc Lou",
      username: "marclou",
      role: "Serial Founder",
      company: "SoloSaaS",
      avatar: "https://picsum.photos/id/102/200/200",
      bio: "Building and scaling micro-SaaS products.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Marketing is just as important as coding. If you build it, they won't come unless you tell them about it.",
    likes: 1200,
    comments: 89,
    commentList: [
      {
        id: "c_u4_2_1",
        userId: "u1",
        user: CURRENT_USER,
        text: "Hard truth for many devs. Distribution is everything.",
        timestamp: "5h ago",
      },
      {
        id: "c_u4_2_2",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "The 50/50 rule: Spend 50% of your time on product and 50% on marketing from day one.",
        timestamp: "2h ago",
      },
    ],
    reposts: 340,
    reposterList: [],
    timestamp: "10h ago",
    tags: ["Marketing", "Startups"],
  },
  {
    id: "p_u4_3",
    userId: "u4",
    user: {
      id: "u4",
      name: "Marc Lou",
      username: "marclou",
      role: "Serial Founder",
      company: "SoloSaaS",
      avatar: "https://picsum.photos/id/102/200/200",
      bio: "Building and scaling micro-SaaS products.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Finding your first 10 customers is the hardest part. After that, it's all about listening to their feedback and iterating.",
    likes: 560,
    comments: 45,
    commentList: [
      {
        id: "c_u4_3_1",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "How did you find your first 10? Cold outreach or existing network?",
        timestamp: "8h ago",
      },
      {
        id: "c_u4_3_2",
        userId: "u4",
        user: {
          id: "u4",
          name: "Marc Lou",
          username: "marclou",
          role: "Serial Founder",
          company: "SoloSaaS",
          avatar: "https://picsum.photos/id/102/200/200",
          bio: "Building and scaling micro-SaaS products.",
          followingIds: [],
          followerIds: [],
        },
        text: "Cold outreach on Twitter and Reddit. I looked for people asking 'How do I do X?' and showed them my tool.",
        timestamp: "4h ago",
      },
    ],
    reposts: 89,
    reposterList: [],
    timestamp: "1d ago",
    tags: ["Customers", "Growth"],
  },
  {
    id: "p_u4_4",
    userId: "u4",
    user: {
      id: "u4",
      name: "Marc Lou",
      username: "marclou",
      role: "Serial Founder",
      company: "SoloSaaS",
      avatar: "https://picsum.photos/id/102/200/200",
      bio: "Building and scaling micro-SaaS products.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Don't overcomplicate your tech stack. Stick to what you know and focus on solving the user's problem.",
    likes: 890,
    comments: 120,
    commentList: [
      {
        id: "c_u4_4_1",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "Boring tech stacks build exciting businesses. 💯",
        timestamp: "1d ago",
      },
      {
        id: "c_u4_4_2",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "The cost of complexity is often hidden until it's too late. Keep it simple, keep it fast.",
        timestamp: "12h ago",
      },
    ],
    reposts: 230,
    reposterList: [],
    timestamp: "3d ago",
    tags: ["TechStack", "Advice"],
  },
  {
    id: "p_u4_5",
    userId: "u4",
    user: {
      id: "u4",
      name: "Marc Lou",
      username: "marclou",
      role: "Serial Founder",
      company: "SoloSaaS",
      avatar: "https://picsum.photos/id/102/200/200",
      bio: "Building and scaling micro-SaaS products.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "The best feature you can add to your product is speed. Nobody likes a slow app.",
    likes: 1500,
    comments: 230,
    commentList: [
      {
        id: "c_u4_5_1",
        userId: "u1",
        user: CURRENT_USER,
        text: "Performance is a feature! Users feel the difference immediately.",
        timestamp: "2d ago",
      },
      {
        id: "c_u4_5_2",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "The 100ms rule: Every interaction should happen in under 100ms or users will perceive it as slow.",
        timestamp: "1d ago",
      },
    ],
    reposts: 450,
    reposterList: [],
    timestamp: "5d ago",
    tags: ["Performance", "UX"],
  },
  {
    id: "p_u6_1",
    userId: "u6",
    user: {
      id: "u6",
      name: "Aarav Mehta",
      username: "aarav_builds",
      role: "First-time Founder",
      company: "EcoStream",
      avatar: "https://picsum.photos/id/103/200/200",
      bio: "Ex-Google PM. Now building EcoStream to decarbonize supply chains.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Supply chain decarbonization is a massive challenge, but the potential impact is huge. Excited to be working on this problem.",
    likes: 340,
    comments: 23,
    commentList: [
      {
        id: "c_u6_1_1",
        userId: "u1",
        user: CURRENT_USER,
        text: "This is a critical space. Rooting for you, Aarav!",
        timestamp: "1h ago",
      },
      {
        id: "c_u6_1_2",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "The UI challenges in visualizing supply chain data must be fascinating. Would love to see how you're handling that.",
        timestamp: "30m ago",
      },
    ],
    reposts: 45,
    reposterList: [],
    timestamp: "5h ago",
    tags: ["ClimateTech", "SupplyChain"],
  },
  {
    id: "p_u6_2",
    userId: "u6",
    user: {
      id: "u6",
      name: "Aarav Mehta",
      username: "aarav_builds",
      role: "First-time Founder",
      company: "EcoStream",
      avatar: "https://picsum.photos/id/103/200/200",
      bio: "Ex-Google PM. Now building EcoStream to decarbonize supply chains.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Transitioning from a PM at a big tech company to a founder has been a wild ride. The learning curve is steep, but I wouldn't trade it for anything.",
    likes: 890,
    comments: 120,
    commentList: [
      {
        id: "c_u6_2_1",
        userId: "u4",
        user: {
          id: "u4",
          name: "Marc Lou",
          username: "marclou",
          role: "Serial Founder",
          company: "SoloSaaS",
          avatar: "https://picsum.photos/id/102/200/200",
          bio: "Building and scaling micro-SaaS products.",
          followingIds: [],
          followerIds: [],
        },
        text: "Welcome to the dark side! It's worth it. 😉",
        timestamp: "3h ago",
      },
      {
        id: "c_u6_2_2",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "The hardest part is unlearning the 'big company' mindset where you have a specialist for everything. Now you're the specialist for everything!",
        timestamp: "1h ago",
      },
    ],
    reposts: 230,
    reposterList: [],
    timestamp: "12h ago",
    tags: ["FounderJourney", "Career"],
  },
  {
    id: "p_u6_3",
    userId: "u6",
    user: {
      id: "u6",
      name: "Aarav Mehta",
      username: "aarav_builds",
      role: "First-time Founder",
      company: "EcoStream",
      avatar: "https://picsum.photos/id/103/200/200",
      bio: "Ex-Google PM. Now building EcoStream to decarbonize supply chains.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Just had a great conversation with a potential investor. They really understood our vision and the problem we're trying to solve.",
    likes: 450,
    comments: 34,
    commentList: [
      {
        id: "c_u6_3_1",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "Vision alignment is key. Good luck with the next steps!",
        timestamp: "5h ago",
      },
      {
        id: "c_u6_3_2",
        userId: "u4",
        user: {
          id: "u4",
          name: "Marc Lou",
          username: "marclou",
          role: "Serial Founder",
          company: "SoloSaaS",
          avatar: "https://picsum.photos/id/102/200/200",
          bio: "Building and scaling micro-SaaS products.",
          followingIds: [],
          followerIds: [],
        },
        text: "Investors bet on the founder as much as the product at this stage. Keep that energy up!",
        timestamp: "2h ago",
      },
    ],
    reposts: 12,
    reposterList: [],
    timestamp: "1d ago",
    tags: ["Fundraising", "Startups"],
  },
  {
    id: "p_u6_4",
    userId: "u6",
    user: {
      id: "u6",
      name: "Aarav Mehta",
      username: "aarav_builds",
      role: "First-time Founder",
      company: "EcoStream",
      avatar: "https://picsum.photos/id/103/200/200",
      bio: "Ex-Google PM. Now building EcoStream to decarbonize supply chains.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "Building a B2B product requires a deep understanding of the customer's workflow. You can't just build something and hope they'll use it.",
    likes: 560,
    comments: 45,
    commentList: [
      {
        id: "c_u6_4_1",
        userId: "u3",
        user: {
          id: "u3",
          name: "Divya Sharma",
          username: "divya_codes",
          role: "Technical Co-founder",
          company: "DesignFlow",
          avatar: "https://picsum.photos/id/177/200/200",
          bio: "Building the future of collaborative design.",
          followingIds: [],
          followerIds: [],
        },
        text: "Workflow integration is the biggest hurdle for B2B adoption.",
        timestamp: "1d ago",
      },
      {
        id: "c_u6_4_2",
        userId: "u2",
        user: {
          id: "u2",
          name: "Sahil Bloom",
          username: "sahil_builds",
          role: "Founder",
          company: "GrowthLoop",
          avatar: "https://picsum.photos/id/65/200/200",
          bio: "Scaling tech startups from 0 to 1.",
          followingIds: [],
          followerIds: [],
        },
        text: "Don't fall into the 'integration trap' early on. Build the core value first, then worry about connecting to every other tool.",
        timestamp: "12h ago",
      },
    ],
    reposts: 89,
    reposterList: [],
    timestamp: "2d ago",
    tags: ["B2B", "ProductManagement"],
  },
  {
    id: "p_u6_5",
    userId: "u6",
    user: {
      id: "u6",
      name: "Aarav Mehta",
      username: "aarav_builds",
      role: "First-time Founder",
      company: "EcoStream",
      avatar: "https://picsum.photos/id/103/200/200",
      bio: "Ex-Google PM. Now building EcoStream to decarbonize supply chains.",
      followingIds: [],
      followerIds: [],
    },
    content:
      "The best advice I've received as a founder: 'Focus on the problem, not the solution.' It's easy to get attached to a specific idea, but the problem is what really matters.",
    likes: 1200,
    comments: 89,
    commentList: [
      {
        id: "c_u6_5_1",
        userId: "u1",
        user: CURRENT_USER,
        text: "Fall in love with the problem, not your solution. Classic and true.",
        timestamp: "2d ago",
      },
      {
        id: "c_u6_5_2",
        userId: "u4",
        user: {
          id: "u4",
          name: "Marc Lou",
          username: "marclou",
          role: "Serial Founder",
          company: "SoloSaaS",
          avatar: "https://picsum.photos/id/102/200/200",
          bio: "Building and scaling micro-SaaS products.",
          followingIds: [],
          followerIds: [],
        },
        text: "This mindset makes pivoting so much easier. If the solution doesn't work, you still have the problem to solve.",
        timestamp: "1d ago",
      },
    ],
    reposts: 340,
    reposterList: [],
    timestamp: "4d ago",
    tags: ["Advice", "Founders"],
  },
];

export const INITIAL_CHATS: Chat[] = [];

export const TRENDING_NEWS: NewsItem[] = [
  {
    id: "n1",
    title: "OpenAI announces new reasoning models",
    source: "TechCrunch",
    time: "1h ago",
    url: "#",
  },
  {
    id: "n2",
    title: "NVIDIA hits new market cap record",
    source: "Bloomberg",
    time: "3h ago",
    url: "#",
  },
  {
    id: "n3",
    title: "Why Rust is winning the backend war",
    source: "Dev.to",
    time: "5h ago",
    url: "#",
  },
  {
    id: "n4",
    title: "Apple Intelligence: New features leaked",
    source: "9to5Mac",
    time: "8h ago",
    url: "#",
  },
  {
    id: "n5",
    title: "The rise of micro-SaaS in 2024",
    source: "IndieHackers",
    time: "12h ago",
    url: "#",
  },
  {
    id: "n6",
    title: "React 19 RC: What you need to know",
    source: "Vercel",
    time: "1d ago",
    url: "#",
  },
];

export const SUGGESTED_FOUNDERS = [
  {
    id: "u_s1",
    name: "Kunal Shah",
    role: "Founder @ CRED",
    avatar: "https://picsum.photos/id/91/100/100",
  },
  {
    id: "u_s2",
    name: "Nithin Kamath",
    role: "CEO @ Zerodha",
    avatar: "https://picsum.photos/id/102/100/100",
  },
  {
    id: "u_s3",
    name: "Sridhar Vembu",
    role: "Founder @ Zoho",
    avatar: "https://picsum.photos/id/129/100/100",
  },
  {
    id: "u_s4",
    name: "Ghazal Alagh",
    role: "Co-founder @ Mamaearth",
    avatar: "https://picsum.photos/id/177/100/100",
  },
  {
    id: "u_s5",
    name: "Bhavish Aggarwal",
    role: "Founder @ Ola",
    avatar: "https://picsum.photos/id/191/100/100",
  },
  {
    id: "u_s6",
    name: "Deepinder Goyal",
    role: "CEO @ Zomato",
    avatar: "https://picsum.photos/id/101/100/100",
  },
];

export const COMMUNITIES: Community[] = [
  { id: "c1", name: "React Native India", members: "12.4k", icon: "⚛️" },
  { id: "c2", name: "SaaS Builders", members: "8.1k", icon: "☁️" },
  { id: "c3", name: "AI/ML Enthusiasts", members: "15.9k", icon: "🤖" },
];
